### PR TITLE
Jfrickmann

### PR DESCRIPTION
**Pull request by jfrickmann**
Added files missing from 2.2 and did some minor modifications

### CODE REVIEW

**Comment by 3djc** [comment]
Thanks Jesper !

**Comment by jfrickmann** [comment]
I have not yet seen the changes in the published version - does someone need to hit a button to make that happen?

**Comment by kilrah** [comment]
It looks like the legacy gitbook app we're on was deactivated for good now... will have to sort out migration.

**Comment by kilrah** [comment]
Should be good now here: https://doc.open-tx.org/opentx-2-3-lua-reference-guide/

**Comment by jfrickmann** [comment]
Thanks 😊

Jesper Frickmann

**Comment by jfrickmann** [comment]
There are still some problems. E.g. part I, mix functions, init function syntax is still missing. But it is there in my local version, and I see the file in the repository.

**Comment by kilrah** [comment]
Looks like the is a mix.md in the root folder and one in the part 1 folder, the one that's used is the latter and has hardcoded links that are invalid, the one in the root folder has relative links and should work but isn't in the right place...

**Comment by jfrickmann** [comment]
I think that I somehow slipped in Git and some things did not get the way that I wanted. I have now forked the repository and will make the pull requests from my own fork. I will be back :)

**Pull request merged**
