### PR TITLE
Font Set Available Characters

### PR DESCRIPTION
**Pull request by RCdiy**

### CODE REVIEW

**Comment by schwabe** [comment]
I think you should rename english to default since they are always available and you forgot German

**Comment by RCdiy** [comment]
I see german
https://github.com/RCdiy/OpenTX-Lua-Reference-Manual/blob/opentx_2.2/appendix/fonts.md

**Comment by RCdiy** [comment]
Changed English to English (Default)

**Comment by schwabe** [comment]
Oh, you are right. I assumed they are alphabetically ordered.

**Comment by RCdiy** [comment]
I followed the order of the files. But yes that can be fixed. What are peoples thoughts on listing the font height?

**Comment by mpaperno** [comment]
Personally I think font metrics are very useful to have/know and it'd be great to have a quick reference source.  Also very nice to have them all on one page like this. 👍

**Comment by RCdiy** [comment]
also any thoughts on editing the drawText page whenre is says look at appendix to have a direct link as well? I've noticed on some pages that links have sometimes been provided to jump to another page...

**Comment by projectkk2glider** [comment]
>also any thoughts on editing the drawText page where it says look at appendix to have a direct link as well? 

This needs to be done in the OpenTX source, I will do that, you will be able to see what I did.

**Comment by projectkk2glider** [comment]
I had to do some tweaking https://github.com/opentx/lua-reference-guide/commit/a1e4d567f58082f09658511e1713f814d89f40f7

**Comment by projectkk2glider** [comment]
@RCdiy Thanks!

**Comment by projectkk2glider** [comment]
This is how I added link in the `lcd.drawText` description: https://github.com/opentx/opentx/commit/2aebcb842a9874af4d1ce7fe4561ce5a3ac6b93d

**Pull request merged**
